### ISSUE TITLE
username and Password not working

### ISSUE THREAD

**Issue by my-side-account** [muneeb706/hrms#3]

**Comment by my-side-account** [comment]
I cloned the repo and tried to login to the using the user name and password given in the seed.js

For eg : 
username ->  salmanN@gmail.com
password -> 123456

![Screenshot_5](https://user-images.githubusercontent.com/81294739/112293335-09ba2f80-8cb8-11eb-9e0e-cb471b31a397.png)



however, it says the wrong password.

**Comment by muneeb706** [comment]
> I cloned the repo and tried to login to the using the user name and password given in the seed.js
> 
> For eg :
> username -> [salmanN@gmail.com](mailto:salmanN@gmail.com)
> password -> 123456
> 
> ![Screenshot_5](https://user-images.githubusercontent.com/81294739/112293335-09ba2f80-8cb8-11eb-9e0e-cb471b31a397.png)
> 
> however, it says the wrong password.

Hi,

Did you run the user-seeder.js first, to store user information in database (MongoDB) ? If not, then you can refer to README (point 7 in how to run the project) for how to run user-seeder.js file.

Thanks

**Comment by my-side-account** [comment]
Thankyou so much for your prompt reply. 

I will check it out.

I was wondering whether I can you cloud database (Atlas) ?

**Comment by muneeb706** [comment]
> Thankyou so much for your prompt reply.
> 
> I will check it out.
> 
> I was wondering whether I can you cloud database (Atlas) ?

Let me know if you are unable to authenticate even after following instructions. It would be great if you can upload dummy data to the cloud. Otherwise, I'll try to work on it at my earliest convenience.
